### ISSUE TITLE
Adyen Java Engineer

### ISSUE THREAD

**Issue by mariofranca-adyen** [Jug-Vale/Jug-Vale.github.io#3]
# [Híbrido] Senior Back-end developer - Adyen

## Adyen

Adyen is the payments platform of choice for the world’s leading companies, delivering frictionless payments across online, mobile and in-store channels. It is the only provider of a modern end-to-end infrastructure, connecting directly to Visa, Mastercard, and consumers’ globally preferred payment methods. With offices around the world, Adyen serves nine of the 10 largest U.S. internet companies and many worldwide retailers. Customers include Meta, Uber, IFood, 99app, Magalu and Spotify.

## Descrição da vaga

As a Senior Java Developer

**You'll have the opportunity to:**

- Work in a platform which process tens of millions payments per day
- Be involved in solutions to provide payments solution to the world's leading companies such as: Meta, Uber, IFood, 99app, Magalu, Spotify and many more
- Integrate to mostly used payment methods in the world, ex.: Visa and Mastercard, but not limiting to those

**What you’ll do**

- Build the global payments engine of the future and ensure that Adyen customers remain at the forefront of innovation.
- Take ownership of systems, features, or frameworks—ranging from medium complexity to large-scale initiatives—ensuring timely delivery, quality, and alignment with project goals.
- Collaborate effectively with your team and across teams, helping to unblock challenges and mentoring less experienced engineers. For larger systems, you’ll lead discussions and guide others through the development lifecycle.
- Design and implement elegant, scalable solutions to complex problems, balancing simplicity with performance. Your work will align with team objectives while minimizing operational overhead and setting new standards where applicable.
- Proactively identify opportunities for improvement, including addressing technical debt. Depending on scope, you may lead or contribute to cross-team initiatives to elevate the overall quality and reliability of our systems.
- Monitor and troubleshoot your systems in production, ensuring consistent behavior and addressing issues promptly. You’ll contribute to or lead incident responses, sharing learnings to improve processes across the organization.

## Local

Hybrid - São José dos Campos / SP / Brazil - being 3 days at the office

## Requisitos

**Who you are**
 - At least 5 years of experience with Java development.
 - You bring strong expertise in Java and related technologies, with a solid grasp of design patterns, testing, and debugging. 
 - Your solutions reflect your depth of knowledge, whether you're solving individual tasks or setting architectural standards.
 - You share knowledge generously, offering meaningful feedback in code reviews and mentoring peers. You may inspire others with your ability to lead initiatives or guide team members through complex challenges.
 - You understand customer needs and business goals, translating them into impactful, high-quality solutions. You’re comfortable prioritizing work that aligns technical priorities with business outcomes.
 - You articulate ideas clearly to technical and non-technical stakeholders. Your documentation is concise and actionable, enabling others to build upon your work independently.
 - You decompose complex problems into actionable tasks with accurate time estimates, coordinating work effectively. For broader initiatives, you’ll take the lead to ensure smooth execution and alignment across teams.

## Benefícios

Read more about the perks here -> https://careers.adyen.com/locations/sao-jose-dos-campos

## Contratação

CLT

## Como se candidatar

Apply here -> https://job-boards.greenhouse.io/adyen/jobs/4813016

### Nível

- Sênior

### Regime

- CLT

### Alocação

- Híbrido

**Comment by pedro-hos** [comment]
https://jug-vale.github.io/vagas/
